apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "production"
      deployment_strategy: "blue_green_service"
      remediation_strategy: "automated"
