--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptndemo
  namespace: keptndemo
  labels:
    app: keptndemo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keptndemo
  template:
    metadata: 
      labels:
        app: keptndemo
    spec:
      containers:
      - image: "{{ .Values.image }}"
        imagePullPolicy: Always
        name: keptndemo
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 25Mi